### ISSUE TITLE
Fcrepo - vypnutí logu na FS

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/osdd-docker-images#1]
Tomcat Fedory plní logy na FS
/usr/local/tomcat/logs/localhost_access_log.2016-*-*.txt

kde po čase dojde místo, Tomcat by měl logovat pouze na konzoli (do ELK)

**Comment by xburda4** [comment]
Dočasne som v docker-compose nahradil konfigurák, aby sa to nelogovalo.
