### ISSUE TITLE
Imageserver - docker-compose

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/osdd-docker-images#4]
Tento compose není funkční 
https://github.com/moravianlibrary/osdd-docker-images/blob/master/imageserver/docker-compose.yml

Je to určitě kvůli tomu, že jsme imageserver přejmenovali na iipimage.

Toto funguje:
https://github.com/moravianlibrary/s2i-meditor/blob/master/docker-compose.kramerius.yml#L80-L89

Ještě by se mi moc hodilo mít přejmenovaný nginx na imageserver (kramerius se taky nejmenuje tomcat), ale z nějakého důvodu se mi pak vrací 502 - je to někde zadrátované v configu? Nenašel jsem to.

**Comment by leiblix** [comment]
To s tím přejmenováním byla asi nějaká jiná chyba, protože dnes mi to na jiném stroji funguje.

Ale zase se mi stalo napoprvé toto:
```2016/12/12 06:23:50 [emerg] 1#1: host not found in upstream "iipimage" in /etc/nginx/conf.d/default.conf:10
nginx: [emerg] host not found in upstream "iipimage" in /etc/nginx/conf.d/default.conf:10
```

Asi přišel na nginx requet dříve než nastartoval iipimage, že? Teď už se mi to zase nedaří zreplikovat :-)

**Comment by dsecik** [comment]
Premenovanie nginx -> imageserver by nemalo nicomu vadit. 

Nazov upstreamu je natvrdo v [konfiguraku](https://github.com/moravianlibrary/osdd-docker-images/blob/master/imageserver/default/nginx/nginx.conf#L10) pretoze ngix by default nepodporuje premenne prostredia v konfigurakoch a nevidim dovod to nejak riesit. V podstate je ten nas image moravianlibrary/nginx:latest  zbytocny pretoze oproti oficialnemu sa lisi len konfigurakom ktory sa tam da mountnut a nasledne upravovat aj za behu. Imho ho mozeme kludne zmazat.

Co sa tyka http 502 iipimage bud z nejakeho dovodu nebezi alebo na ten kontainer ngix nevidi (pod aliasom ktory je v konfiguraku)

**Comment by leiblix** [comment]
> Nazov upstreamu je natvrdo v konfiguraku pretoze ngix by default nepodporuje premenne prostredia v konfigurakoch a nevidim dovod to nejak riesit. V podstate je ten nas image moravianlibrary/nginx:latest zbytocny pretoze oproti oficialnemu sa lisi len konfigurakom ktory sa tam da mountnut a nasledne upravovat aj za behu. Imho ho mozeme kludne zmazat.

Ten název upstreamu mi nevadí. Rozhodně moravianlibrary/iipsrv-nginx nemazat, to je právě dobře, že ten konfigurační soubor je schovaný v image. (musel bych ten konfigurák cpát do kódu s2i builderů, kde imageserver používám na testy).

Ten nalinkovaný docker-compose nefunguje, buď ho opravme (pravděpodobně stačí přejmenovat tu jednu service), nebo ho smažme.
